[package]
name = "cfgo"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["cookies", "json"] }
scraper = "0.17"
colored = "2.0"
clap = { version = "4.0", features = ["derive"] }
rpassword = "5.0"
